name: 🚀 Enhancement
description: Suggest an enhancement or improvement to an existing feature!
title: '[Enhancement]: '
labels: ['type: enhancement']
body:
  - type: textarea
    id: howitworks
    attributes:
      label: My idea
      description: Describe the changes you're suggesting and how they would work.
      placeholder: Add an option to...
    validations:
      required: true
