name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10.7.1

      - name: Run type checks
        run: pnpm tsc --noEmit

      - name: Run tests
        run: pnpm test

      - name: Verify linting and formatting
        run: pnpm lint && pnpm format --check
